### ISSUE TITLE
2018-09-26 feedback.

### ISSUE THREAD

**Issue by blinks** [blinks/ozymandias#51]
Rules and cards from commit 7691f9999df8561a75ae07d9f97652132b7122f9

- Worried about no-money start, but it would have been fine. (Tried starting with $10 anyway.)
- Lots of single-color stacks, dividends for them seem degenerate, at least annoying.
- One-color war is strange.
- Dividend counting is a bit painful to multiply out.
- Ability timing (on the cards) is super-vague.
- Big wars (many disks) are monstrous in how they affect faction value.
- Dividend value seemed like it was bigger than card value in this game (where red jumped 9 steps at once, and most factions ended at 6 or 10, and I had four cards vaulted, more than anyone else).
- Sector placement just didn't happen -- not enough incentive for it.
- Card value, and how it applied to expansion, was easy to forget. Stack height limits too.

Final scores:

- Adam: 129 VPs (90 from red cards)
- Gary: 119 VPs (mostly dividends)
- Jeff: 120 VPs (half and half)

Possible changes:

- Only count each color once-per-stack for dividends.
- Drop sector cards. Instead:
- Trade any card for _hex_ sector placement (and income), then buy back up to seven.
   - But what does sector value do?
   - And where do the abilities go?
   - Place disks on the corners, like Catan.
- Play with a minimal deck; just a normal deck of cards, perhaps.
- Rename "war" to "crisis", so a single color still makes sense.

**Comment by garykac** [comment]
Though "war"/"uprising" sounds so much more thematic than "crisis"

**Comment by blinks** [comment]
It's a minimal change. The core of it is that I'm keeping one-color "fights" possible.

**Comment by blinks** [comment]
Now that sector cards aren't clogging your hand, I think I'll drop hand size to five cards, too.

Crisis should be a simultaneous "trick-taking" thing, where only the high card (bolstered by the disks at that sector) matters.

To that end, Gary suggests that as low-value cards are more difficult to vault, perhaps they should count as more shares at the end of the game, and I'll take it.

Open questions:
- Sector differentiation?
- Is the vault bonus enough to make it a difficult decision what to use in a war?

**Comment by blinks** [comment]
More open questions:
- Should the starting values be randomized?

**Comment by blinks** [comment]
To clarify ability timing (and allow us to use the old card templates): card effects are activated through one of the three actions.
- Exploration: when a sector is placed next to its faction.
- Expansion: when a city is placed matching, or ruling its faction.
- Crisis: when the card is used in a crisis.

**Comment by blinks** [comment]
For the playtest, all cards will have an expansion ability that pays dividends, to match the existing ruleset.

**Comment by blinks** [comment]
We'll play today with un-differentiated sectors and only default abilities, and see how that goes.
